export interface ExperienceEntry {
  id: string;
  organization: string;
  organizationUrl?: string;
  role: string;
  period: string;
  location?: string;
  image: string;
  paragraphs: string[];
  focus: string[];
  projectIds: string[];
  newsIds: number[];
}

export const experienceIntro = {
  title: "The work that motivates me",
  paragraphs: [
    "I lead marketing and communications at Summation, a decision-grade AI company in the Seattle area.",
    "My work sits at the intersection of AI, emerging tech, communications, operations, and the systems people use every day.",
    "For me, that has meant building programs around AI literacy, supporting early product feedback, researching how technology changes society, designing digital and IRL communications systems, and helping teams leverage communication tools to achieve their goals.",
    "I do not come from a traditional technical background. A lot of my growth has come from learning quickly, figuring out new tools, and using AI to build systems I would not have been able to build a few years ago.",
    "That is the part I'm most excited by: not just what new technology can do, but the ways it can enable people to do good.",
  ],
};

export const experienceEntries: ExperienceEntry[] = [
  {
    id: "summation-ai",
    organization: "Summation",
    organizationUrl: "https://www.summation.com/",
    role: "Marketing and Communications",
    period: "2026-Present",
    location: "Seattle, Washington",
    image: "/webpreview-linkedin.png",
    paragraphs: [
      "I lead marketing and communications at Summation, a decision-grade AI company that connects to live business data and helps enterprise teams understand what changed, why it happened, and what to do next.",
      "The role brings together my experience in AI, strategy, writing, and translating complex technology into language people can trust and act on.",
    ],
    focus: ["AI marketing", "communications strategy", "go-to-market", "enterprise AI"],
    projectIds: [],
    newsIds: [],
  },
  {
    id: "fulbright-taiwan",
    organization: "Fulbright Taiwan",
    organizationUrl: "https://www.fulbright.org.tw/",
    role: "Fulbright Scholar",
    period: "Aug 2025-Aug 2026",
    image: "/experience/fb.jpeg",
    paragraphs: [
      "I created and led an OpenAI-supported AI literacy program for educators in Taiwan, focused on helping non-technical users understand and apply AI in real classroom workflows.",
      "I designed six applied sessions on AI use cases, prompt design, LLM basics, and safe adoption, then led an LLM fundamentals and alignment workshop at a 250+ person international education conference.",
      "Alongside the AI education work, I coach elementary school soccer and published a Substack with OpenAI highlighting nine high-impact education use cases for ChatGPT.",
    ],
    focus: ["AI enablement", "user education", "community comms", "curriculum design"],
    projectIds: ["fulbright-focus-group-sponsored-by-openai", "ai-literacy-workshop-for-educators"],
    newsIds: [1, 7],
  },
  {
    id: "csg-ai-index",
    organization: "Council of State Governments",
    organizationUrl: "https://www.csg.org/",
    role: "AI Adoption Research",
    period: "Jun 2025-Jul 2025",
    location: "Washington DC-Baltimore Area",
    image: "/experience/csg.jpeg",
    paragraphs: [
      "I built a 900-input index measuring AI adoption and preparedness across 56 U.S. states and territories.",
      "I created a normalized scoring rubric, collected and cleaned data, and helped turn a messy policy landscape into something easier to compare and act on.",
      "I also supported planning for an AI policy summit by mapping 50+ technology partners and structuring outreach.",
    ],
    focus: ["AI policy research", "data systems", "partner mapping", "strategy support"],
    projectIds: ["artificial-intelligence-in-state-government-index"],
    newsIds: [],
  },
  {
    id: "openai-chatgpt-lab",
    organization: "OpenAI",
    organizationUrl: "https://openai.com/",
    role: "ChatGPT Lab",
    period: "Mar 2025-Present",
    image: "/experience/oai.jpg",
    paragraphs: [
      "I'm part of the first cohort of OpenAI's ChatGPT Lab, where I test new ChatGPT products and share structured feedback with product and go-to-market teams.",
      "I co-authored a book featuring 100 uses for ChatGPT, with a focus on practical workflows and real user behavior.",
      "I also informed deployment of major marketing campaigns and product launches, including Pulse and Atlas.",
    ],
    focus: ["product feedback", "GTM insight", "AI education", "user behavior", "early testing"],
    projectIds: ["fulbright-focus-group-sponsored-by-openai"],
    newsIds: [5, 9, 8],
  },
  {
    id: "washu-head-ta",
    organization: "Washington University in St. Louis",
    organizationUrl: "https://washu.edu/",
    role: "Assistant Teaching",
    period: "Jan 2024-May 2024; Jan 2025-Apr 2025",
    image: "/experience/washu2.jpg",
    paragraphs: [
      "I supported political science instruction across two teaching appointments, first as a teaching assistant and later as head teaching assistant for a 150 person seminar course.",
      "I provided guidance for departmental AI policy, delivered feedback on 120+ student products, and managed a teaching team of 12.",
      "The work combined classroom operations, student writing feedback, staff coordination, and practical thinking about how AI tools should be handled in undergraduate courses.",
    ],
    focus: ["teaching operations", "team management", "student feedback"],
    projectIds: [],
    newsIds: [],
  },
  {
    id: "boehringer-communications-strategy",
    organization: "Boehringer Ingelheim",
    organizationUrl: "https://www.boehringer-ingelheim.com/",
    role: "Communications Strategy and Operations",
    period: "May 2024-Aug 2025",
    location: "Ridgefield, Connecticut, United States",
    image: "/experience/boehringer.jpg",
    paragraphs: [
      "I worked across communications, operations, internal strategy, employee engagement, and sustainability initiatives for two internal functions.",
      "I led major rebrand and strategy work, coordinated the first quantitative performance benchmark for CSR programs, and completed the first comprehensive report for company sustainability initiatives across the U.S.",
      "I built a company-wide newsletter system with an 80% open rate, shipped dozens of major cross-functional communications assets, and redesigned internal messaging and UX around employee volunteering, helping increase annual participation by 25%.",
    ],
    focus: ["internal operations", "cross-functional execution", "systems design", "stakeholder communications"],
    projectIds: ["boehringer-cares-foundation-rebrand-strategy-shift", "sustainable-development-health-access-report"],
    newsIds: [],
  },
  {
    id: "washu-ai-journalism",
    organization: "Washington University in St. Louis",
    organizationUrl: "https://washu.edu/",
    role: "AI, Digital Platforms, and Journalism Research",
    period: "Mar 2024-May 2025",
    location: "St Louis, Missouri, United States",
    image: "/experience/washu2.jpg",
    paragraphs: [
      "I authored a 100+ page honors thesis on AI, digital platforms, and local journalism.",
      "I conducted 17 in-depth interviews with Australian journalists, editors, owners, and policy experts. The project explored journalism as a public good, platform incentives, economic decline, and the uncertainty surrounding generative AI.",
    ],
    focus: ["user research", "qualitative analysis", "platform strategy", "longform synthesis"],
    projectIds: ["senior-thesis-local-journalism", "political-reporting-at-washu"],
    newsIds: [12, 6, 11],
  },
  {
    id: "isaac-seiler-strategies",
    organization: "Isaac Seiler Strategies",
    role: "Founder and Consultant",
    period: "Jan 2024-Apr 2025",
    image: "/project-images/politicalconsult.jpg",
    paragraphs: [
      "I founded an independent consultancy supporting local and federal candidates through campaign websites, digital strategy, and rapid-response communications.",
      "One campaign I supported was Allyson Damikolas for Tustin Unified School Board in California, where I led digital and communications strategy and built the campaign website as a central hub for messaging, organizing, and voter-facing information.",
      "I also managed social media messaging and supported rapid-response and crisis communications during high-pressure moments in the race.",
    ],
    focus: ["campaign websites", "digital strategy", "rapid response", "communications advising"],
    projectIds: ["communications-consultancy-supporting-local-candidates"],
    newsIds: [],
  },
  {
    id: "washu-staff-writer",
    organization: "Washington University in St. Louis",
    organizationUrl: "https://washu.edu/",
    role: "Staff Writer",
    period: "Sep 2023-Apr 2025",
    location: "St Louis, Missouri, United States",
    image: "/experience/washu2.jpg",
    paragraphs: [
      "I wrote 9+ journalism pieces for WashU's independent newspaper, Student Life.",
      "My reporting focused on campus politics, protest, elections, free speech, governance, and institutional accountability.",
    ],
    focus: ["reporting", "campus politics", "student journalism"],
    projectIds: ["political-reporting-at-washu"],
    newsIds: [11],
  },
  {
    id: "us-house",
    organization: "U.S. House of Representatives",
    organizationUrl: "https://www.house.gov/",
    role: "Communications Strategy and Operations",
    period: "Nov 2022-Jun 2023",
    location: "Washington DC-Baltimore Area",
    image: "/project-images/caphill.jpg",
    paragraphs: [
      "I helped build the communications function for a new congressional office from the ground up.",
      "I created workflows, managed press outreach, organized events and official travel, and helped the office reach 350,000 people weekly.",
      "I secured 34+ interviews with national outlets including The New York Times, CNN, and MSNBC.",
    ],
    focus: ["operational setup", "communications strategy", "rapid execution", "stakeholder management"],
    projectIds: ["congressional-office-setup-100-day-report"],
    newsIds: [],
  },
  {
    id: "scholten-campaign",
    organization: "Scholten for Congress",
    organizationUrl: "https://hillaryscholten.com/",
    role: "Communications Director and Transition Aide",
    period: "Jun 2022-Nov 2022",
    location: "Grand Rapids, Michigan, United States",
    image: "/experience/campaignscholten.jpeg",
    paragraphs: [
      "I worked across digital communications, content, events, and logistics on a competitive congressional campaign.",
      "I helped run a cross-platform digital program generating 1M+ weekly impressions and $30k+ in organic fundraising. I also supported logistics for 100+ events with elected officials, cabinet secretaries, senators, and community leaders.",
    ],
    focus: ["digital strategy", "campaign operations", "audience growth", "event logistics"],
    projectIds: [],
    newsIds: [],
  },
  {
    id: "progressive-turnout-project",
    organization: "Progressive Turnout Project",
    organizationUrl: "https://turnoutpac.org/",
    role: "Fellow",
    period: "Aug 2022-Nov 2022",
    image: "/experience/progturnout.jpeg",
    paragraphs: [
      "As a fellow for the 2022 Midterms, I underwent training and support to build my skills around campaign strategy.",
      "Topics included messaging, organizing, and digital mobilization.",
    ],
    focus: ["campaign strategy", "organizing", "digital mobilization"],
    projectIds: [],
    newsIds: [],
  },
  {
    id: "dccc-democracy-summer",
    organization: "DCCC",
    organizationUrl: "https://dccc.org/",
    role: "Fellow",
    period: "Jun 2022-Aug 2022",
    image: "/experience/DCCC.jpeg",
    paragraphs: [
      "The Democracy Summer program is the Democratic Congressional Campaign Committee's premier fellowship for college students interested in congressional politics.",
      "Selected as a part of a nationwide cohort, I got access to training and support as I interned on a high profile congressional campaign.",
    ],
    focus: ["congressional politics", "campaign training", "field support"],
    projectIds: [],
    newsIds: [],
  },
  {
    id: "institute-for-nonprofit-news",
    organization: "Institute for Nonprofit News",
    organizationUrl: "https://inn.org/",
    role: "Digital Platforms and Journalism Research",
    period: "Dec 2021-Sep 2022",
    location: "Grand Rapids, Michigan, United States",
    image: "/project-images/nonprofitnews.jpg",
    paragraphs: [
      "I contributed to research on nonprofit newsrooms and digital ecosystems for the 2022 INN Index.",
      "I cleaned, synthesized, and organized complex data from 100+ editors, helping make newsroom trends easier to understand and compare.",
    ],
    focus: ["data cleaning", "research synthesis", "ecosystem analysis", "editorial operations"],
    projectIds: ["2022-institute-for-nonprofit-news-index-survey"],
    newsIds: [],
  },
];
